trigger:
  branches: 
    include: 
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  - name: godot_version
    value: '4.3'

steps:
  - checkout: self

  - task: PowerShell@2
    displayName: 'Download Godot'
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_win64.exe.zip -OutFile $(Agent.TempDirectory)/godot.zip

  - task: ExtractFiles@1
    displayName: "Extract Godot executable files"
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)/godot.zip'
      destinationFolder: '$(Agent.ToolsDirectory)/godot'

  - task: PowerShell@2
    displayName: 'Build Project Godot'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "$(Agent.ToolsDirectory)"
        Get-ChildItem -Path "$(Agent.ToolsDirectory)\*.*" -Recurse -Force
        
