trigger:
  branches: 
    include: 
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  - name: godot_version
    value: '4.3'

steps:
  - checkout: self

  - task: PowerShell@2
    displayName: 'Download Godot'
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest https://github.com/godotengine/godot-builds/releases/download/Godot_v$(godot_version)-stable_win64.exe.zip -OutFile $(Agent.TempDirectory)/godot.zip

  - task: ExtractFiles@1
    displayName: "Extract Godot executable files"
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)/godot.zip'
      destinationFolder: '$(Agent.ToolsDirectory)'
